# Generated by Django 3.2.20 on 2023-07-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lng', 'lat')},
        ),
    ]
