# Generated by Django 3.2.20 on 2023-07-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='', verbose_name=' Фотография'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Место'),
            preserve_default=False,
        ),
    ]
